//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4_Ad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdjVoucher()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int AdjVoucherId { get; set; }
        public string ItemId { get; set; }
        public Nullable<int> QuantityAdj { get; set; }
        public string Reason { get; set; }
        public Nullable<int> RequestEmpNum { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> ApprovalEmpNum { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    
        public virtual ItemList ItemList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
