//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4_Ad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemList()
        {
            this.AdjVouchers = new HashSet<AdjVoucher>();
            this.ItemSuppliers = new HashSet<ItemSupplier>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.RequDetails = new HashSet<RequDetail>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string ItemId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Description { get; set; }
        public int ReOrderLevel { get; set; }
        public Nullable<int> ReOrderQty { get; set; }
        public string UOM { get; set; }
        public string Bin { get; set; }
        public Nullable<int> Stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjVoucher> AdjVouchers { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSupplier> ItemSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequDetail> RequDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
