//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4_Ad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.RequDetails = new HashSet<RequDetail>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int RequId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string Status { get; set; }
        public string SignBy { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string Note { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequDetail> RequDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
