//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4_Ad
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequDetail
    {
        public int RequDetailId { get; set; }
        public Nullable<int> RequId { get; set; }
        public string ItemId { get; set; }
        public Nullable<int> RequestedQuantity { get; set; }
        public Nullable<int> OutstandingQuantity { get; set; }
    
        public virtual ItemList ItemList { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
